import { buildDataset } from '../../buildDataset'
import type { FloorDataset } from '../../../domain/spatial'

/**
 * Floor 16 dataset. The JSON lives at `data/floors/floor-16/` in the repository
 * root, not here, because the backend reads the same files to decide which seat
 * codes exist — it cannot reach inside `frontend/`. All of it is GENERATED by
 * `tools/floorplan_extract/extract_floor.py floor16` — do not edit by hand.
 */
export default async function loadFloor16(): Promise<FloorDataset> {
  const [layout, zones, workstations, objects, obstacles, extraction] = await Promise.all([
    import('@data/floors/floor-16/floor16.layout.json'),
    import('@data/floors/floor-16/floor16.zones.json'),
    import('@data/floors/floor-16/floor16.workstations.json'),
    import('@data/floors/floor-16/floor16.objects.json'),
    import('@data/floors/floor-16/floor16.obstacles.json'),
    import('@data/floors/floor-16/floor16.extraction.json'),
  ])
  return buildDataset(
    {
      layout: layout.default,
      zones: zones.default,
      workstations: workstations.default,
      objects: objects.default,
      obstacles: obstacles.default,
      extraction: extraction.default,
    },
    {
      // Not stated on the PDF; confirmed by the team (CAD xref layers are prefixed "TNP").
      building: { id: 'building-technopark', name: 'Technopark' },
      sourceName: '260710_VSF_Layout tang 16.pdf',
    },
  )
}
