import { buildDataset } from '../../buildDataset'
import type { FloorDataset } from '../../../domain/spatial'

/**
 * Floor 16 dataset. All JSON files in this folder are GENERATED by
 * `tools/floorplan_extract/extract_floor.py floor16` — do not edit by hand.
 */
export default async function loadFloor16(): Promise<FloorDataset> {
  const [layout, zones, workstations, objects, extraction] = await Promise.all([
    import('./floor16.layout.json'),
    import('./floor16.zones.json'),
    import('./floor16.workstations.json'),
    import('./floor16.objects.json'),
    import('./floor16.extraction.json'),
  ])
  return buildDataset(
    {
      layout: layout.default,
      zones: zones.default,
      workstations: workstations.default,
      objects: objects.default,
      extraction: extraction.default,
    },
    {
      // Not stated on the PDF; confirmed by the team (CAD xref layers are prefixed "TNP").
      building: { id: 'building-technopark', name: 'Technopark' },
      sourceName: '260710_VSF_Layout tang 16.pdf',
    },
  )
}
